services:
  - type: web
    name: angela-memoria
    env: python
    plan: free
    autoDeploy: true
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn angela_server:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: FIREBASE_STORAGE_BUCKET
        value: angela-memoria.appspot.com   # <-- cámbialo si tu bucket es otro
      - key: FIREBASE_KEY_JSON
        sync: false  # Valor se define desde el panel (no en el repo)
